server:
  name: "project-api"
  addr: "127.0.0.1:80"

zap:
  debugFileName: "D:\\go\\project\\logs\\project_api\\debug\\project-debug.log"
  infoFileName: "D:\\go\\project\\logs\\project_api\\info\\project-info.log"
  warnFileName: "D:\\go\\project\\logs\\project_api\\error\\project-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3

etcd:
  addrs:
    - "127.0.0.1:2379"

