server:
  name: "project-project"
  addr: "127.0.0.1:8081"

zap:
  debugFileName: "D:\\go\\project\\logs\\project_project\\debug\\project-debug.log"
  infoFileName: "D:\\go\\project\\logs\\project_project\\info\\project-info.log"
  warnFileName: "D:\\go\\project\\logs\\project_project\\error\\project-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

grpc:
  addr: "127.0.0.1:8882"
  etcdAddr: "127.0.0.1:8882"
  name: "project"
  verison: "1.0.0"
  weight: 2

etcd:
  addrs:
    - "127.0.0.1:2379"

mysql:
  username: root
  password: root
  host: 127.0.0.1
  port: 3306
  db: msproject

db:
  separation: false
  master:
    name: master
    username: root
    password: root
    host: 127.0.0.1
    port: 3306
    db: msproject
  slave:
    - username: root
      password: root
      host: 127.0.0.1
      port: 3306
      db: msproject_slave1
      name: slave1
    - username: root
      password: root
      host: 127.0.0.1
      port: 3306
      db: msproject_slave2
      name: slave2

jwt:
  accessExp: 7
  refreshExp: 14
  accessSecret: msproject
  refreshSecret: ms_pproject

kafka:
  addr:
    - 127.0.0.1:9092
  group: cache_group
  topic: msproject_cache

jaeger:
  endpoints: "http://127.0.0.1:14268/api/traces"